dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=klu
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-musl
    os: osx
  - env: TARGET=x86_64-apple-darwin
    os: osx
  - env: TARGET=x86_64-pc-windows-gnu
  - env: TARGET=x86_64-unknown-linux-gnu
    rust: nightly
  - env: TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
before_install:
- set -e
- rustup self update
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - cli
notifications:
  email:
    on_success: never
deploy:
  provider: releases
  api_key:
    secure: ShWhw0FbxlTCh4N9n61zEXb+AN35oinZDn3aJI9ZNuVU4+fdg2EF45XP7sYPoSjkXiK1DpHAoFix0AJCXhdTAEFazXLkFDNDhcItMNbwL0r9/ctjE8g0VkGfOJFgDIGYcwyJggdR3D92e5osVwDd9DT/fr2EI3IquUwbWRhvZ2VyBKrfyj/ObhhwLkNGRPm761mypSEzwoBwKOlm4xePgfyRYD51oMq6nzAj7m8mY4Lhg2kVvI+Sb7qQOHwbF835SwA9P0uQe/c0EzpzTTji8guOtqrY+8ImEt7PzMin0ZnYusJvwgz12IynNjjypLvLXFAtHG99XKVqaS/Q+2w7a/ZQoL9RP1vGMbwPR5BdsG3MOhxbjdamDAA80NOPw5XgcQ3ZWuLog/HuabCNSNObGcKlzzIouIBstDEr3gFdB5imPwnOybRSsriy67H/bxJPmvPkdo1lvlX4+BLKuGTRj2x7w2LLZux/VDCmKuDmqI6sEgOyFUWg1sck05MgM8lVvJjPptD+6xSFVQt+4t0GYTbQ7WuVjKXOznaYfaENl+YHvsaDnJf7gLgMflU43b8eHKqw+91SJljmuXCAbIQwv19hN2ix4cAUCW/AHwnoAbAmCvDhyzvPa8mYmRKmmwniqI7QEL89x7uWWKpI/FSKPvvqm/KgNQBg2+D3cZUjKow=
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $RUST_VERSION = stable
    repo: Maix0/klu_format
    branch: cli
    tags: false
  skip_cleanup: true 
